import React, { useState } from 'react';
import {
  View,
  Text,
  StyleSheet,
  SafeAreaView,
  ScrollView,
  TextInput,
  TouchableOpacity,
  KeyboardAvoidingView,
  Platform,
} from 'react-native';
import { router } from 'expo-router';
import { Colors, FontFamily, Shadow, Radius } from '@/constants/theme';
import { AppButton } from '@/components/shared/AppButton';
import { loginUser } from '@/lib/api';
import { setAccessToken } from '@/lib/session';

export default function LoginScreen() {
  const [username, setUsername] = useState('');
  const [password, setPassword] = useState('');
  const [error, setError] = useState('');
  const [loading, setLoading] = useState(false);

  const handleLogin = async () => {
    if (loading) return;
    setError('');
    setLoading(true);

    try {
      const token = await loginUser({ username, password });
      await setAccessToken(token.access_token);
      router.replace('/(tabs)');
    } catch (err) {
      const message = err instanceof Error ? err.message : 'Login failed';
      setError(message);
    } finally {
      setLoading(false);
    }
  };

  return (
    <SafeAreaView style={styles.safe}>
      <KeyboardAvoidingView
        behavior={Platform.OS === 'ios' ? 'padding' : undefined}
        style={{ flex: 1 }}
      >
        {/* Red wave header */}
        <View style={styles.header}>
          <Text style={styles.headerEmoji}></Text>
          <Text style={styles.headerTitle}>Welcome back,{'\n'}Mama!</Text>
          <Text style={styles.headerSub}>Sign in to check on your little one</Text>
        </View>

        {/* Wave curve */}
        <View style={styles.wave} />

        <ScrollView
          contentContainerStyle={styles.body}
          keyboardShouldPersistTaps="handled"
        >
          {/* Username */}
          <View>
            <Text style={styles.label}>USERNAME</Text>
            <TextInput
              style={styles.input}
              value={username}
              onChangeText={setUsername}
              placeholder="your username"
              placeholderTextColor={Colors.gray500}
              autoCapitalize="none"
            />
          </View>

          {/* Password */}
          <View>
            <Text style={styles.label}>PASSWORD</Text>
            <TextInput
              style={styles.input}
              value={password}
              onChangeText={setPassword}
              placeholder="••••••••"
              placeholderTextColor={Colors.gray500}
              secureTextEntry
            />
          </View>

          {/* Forgot password */}
          <TouchableOpacity onPress={() => {}}>
            <Text style={styles.forgot}>Forgot password? →</Text>
          </TouchableOpacity>

          {/* Sign in button */}
          <AppButton
            label={loading ? 'Signing In...' : 'Sign In'}
            variant="red"
            onPress={handleLogin}
          />

          {error ? <Text style={styles.errorText}>{error}</Text> : null}

          {/* Sign up link */}
          <View style={styles.footer}>
            <Text style={styles.footerText}>New here? </Text>
            <TouchableOpacity onPress={() => router.push('/(auth)/signup')}>
              <Text style={styles.footerLink}>Create an account</Text>
            </TouchableOpacity>
          </View>

          <View>
            <Text style={styles.label}> This recommendation is generated by an AI assistant
              and is not a substitute for professional medical advice. Always consult
              a qualified pediatrician before making dietary changes for your baby.</Text>
          </View>
        </ScrollView>
      </KeyboardAvoidingView>
    </SafeAreaView>
  );
}

const styles = StyleSheet.create({
  safe: {
    flex: 1,
    backgroundColor: Colors.cream,
  },

  // Header
  header: {
    backgroundColor: Colors.red,
    paddingTop: 20,
    paddingHorizontal: 24,
    paddingBottom: 48,
  },
  headerEmoji: {
    fontSize: 32,
    marginBottom: 8,
  },
  headerTitle: {
    fontFamily: FontFamily.display,
    fontSize: 28,
    color: Colors.white,
    textShadowColor: 'rgba(0,0,0,0.15)',
    textShadowOffset: { width: 2, height: 2 },
    textShadowRadius: 0,
    lineHeight: 34,
  },
  headerSub: {
    fontFamily: FontFamily.body,
    fontSize: 13,
    color: 'rgba(255,255,255,0.8)',
    marginTop: 6,
  },

  // Wave curve between header and body
  wave: {
    height: 32,
    backgroundColor: Colors.cream,
    borderTopLeftRadius: 32,
    borderTopRightRadius: 32,
    marginTop: -28,
  },

  // Body
  body: {
    paddingHorizontal: 24,
    paddingTop: 8,
    paddingBottom: 40,
    gap: 16,
  },

  // Input
  label: {
    fontFamily: FontFamily.bodyBlack,
    fontSize: 11,
    letterSpacing: 1,
    color: Colors.gray700,
    marginBottom: 6,
  },
  input: {
    backgroundColor: Colors.white,
    borderWidth: 3,
    borderColor: Colors.outline,
    borderRadius: Radius.lg,
    paddingVertical: 13,
    paddingHorizontal: 16,
    fontFamily: FontFamily.body,
    fontSize: 15,
    color: Colors.gray900,
    ...Shadow.sm,
  },

  // Forgot
  forgot: {
    fontFamily: FontFamily.bodyBold,
    fontSize: 13,
    color: Colors.red,
    textAlign: 'right',
    marginTop: -6,
  },

  // Footer
  footer: {
    flexDirection: 'row',
    justifyContent: 'center',
    marginTop: 4,
  },
  footerText: {
    fontFamily: FontFamily.body,
    fontSize: 14,
    color: Colors.gray500,
  },
  footerLink: {
    fontFamily: FontFamily.bodyBold,
    fontSize: 14,
    color: Colors.red,
    textDecorationLine: 'underline',
  },
  errorText: {
    fontFamily: FontFamily.body,
    fontSize: 13,
    color: Colors.redDark,
    textAlign: 'center',
  },
});